packages:
  - apps/*
  - packages/*

allowBuilds:
  prisma: true
  "@prisma/engines": true
  esbuild: true
  workerd: false
  msgpackr-extract: true
  sharp: true
  "@swc/core": false
  "@parcel/watcher": false
  "@google/genai": false
  protobufjs: false
