/**
 * Seed content for Phase 3 (templates & libraries). Split out of seed.ts to keep that file short.
 * Everything here is original: hand-written SVG stickers (generated by a small parametric helper,
 * not traced from any third party) and template compositions built from editor-core node types only.
 *
 * Size presets duplicated (intentionally) from apps/web/lib/templates.ts: this package can't import
 * from apps/web (wrong dependency direction), and the two agents building templates vs. seed data
 * ran in parallel worktrees. Fold into packages/shared at merge time if useful to other agents.
 */

// ---------- Size presets ----------

export const SIZE_PRESETS = [
  { id: "instagram_post", width: 1080, height: 1080 },
  { id: "instagram_story", width: 1080, height: 1920 },
  { id: "facebook_post", width: 1200, height: 630 },
  { id: "youtube_thumbnail", width: 1280, height: 720 },
  { id: "pinterest_pin", width: 1000, height: 1500 },
  { id: "business_card", width: 1050, height: 600 },
  { id: "flyer_letter", width: 1700, height: 2200 },
  { id: "poster", width: 1800, height: 2700 },
  { id: "presentation_16_9", width: 1920, height: 1080 },
  { id: "resume_a4", width: 1240, height: 1754 },
  { id: "invitation", width: 1200, height: 1800 },
  { id: "product_square", width: 1000, height: 1000 },
  { id: "banner_ad", width: 1200, height: 628 },
] as const;

export type SizePresetId = (typeof SIZE_PRESETS)[number]["id"];

export function presetSize(id: SizePresetId): { width: number; height: number } {
  const p = SIZE_PRESETS.find((s) => s.id === id);
  if (!p) throw new Error(`unknown size preset ${id}`);
  return { width: p.width, height: p.height };
}

// ---------- Brand-ish palette reused for sticker colors ----------

export const PALETTE = {
  ember: "#FF6A3D",
  violet: "#7C5CFF",
  teal: "#2EF2C9",
  pink: "#FF5CA8",
  gold: "#FFC24D",
} as const;

// ---------- Original SVG stickers (parametric: 8 shapes × 5 colors + 4 bonus) ----------

const SHAPES: Record<string, (c: string) => string> = {
  dot: (c) => `<circle cx="32" cy="32" r="26" fill="${c}"/>`,
  ring: (c) => `<circle cx="32" cy="32" r="23" fill="none" stroke="${c}" stroke-width="7"/>`,
  star4: (c) => `<path d="M32 3 L38 26 L61 32 L38 38 L32 61 L26 38 L3 32 L26 26 Z" fill="${c}"/>`,
  star5: (c) =>
    `<path d="M32 3 L39.5 23.5 L61 24 L43.5 37 L50 58 L32 46 L14 58 L20.5 37 L3 24 L24.5 23.5 Z" fill="${c}"/>`,
  blob: (c) => `<path d="M45 9c10 5 17 15 15 27-2 12-15 21-29 21S4 55 5 41 13 11 27 7s13-2 18 2Z" fill="${c}"/>`,
  bubble: (c) =>
    `<rect x="6" y="9" width="52" height="33" rx="12" fill="${c}"/><path d="M18 42 L18 57 L33 42 Z" fill="${c}"/>`,
  bolt: (c) => `<path d="M37 2 L13 36 L28 36 L23 62 L51 25 L35 25 Z" fill="${c}"/>`,
  hexagon: (c) => `<path d="M32 3 L58 17.5 L58 46.5 L32 61 L6 46.5 L6 17.5 Z" fill="${c}"/>`,
};

function svg(inner: string): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">${inner}</svg>`;
}

export interface SeedSticker {
  slug: string;
  svg: string;
  tags: string[];
}

export function buildStickers(): SeedSticker[] {
  const out: SeedSticker[] = [];
  for (const [shapeName, draw] of Object.entries(SHAPES)) {
    for (const [colorName, hex] of Object.entries(PALETTE)) {
      out.push({ slug: `${shapeName}-${colorName}`, svg: svg(draw(hex)), tags: [shapeName, colorName, "geometric"] });
    }
  }
  // Bonus multi-element stickers (not part of the shape × color grid).
  out.push({
    slug: "confetti-mix",
    tags: ["confetti", "party", "multicolor"],
    svg: svg(
      `<circle cx="14" cy="16" r="5" fill="${PALETTE.ember}"/><rect x="38" y="8" width="10" height="10" rx="2" fill="${PALETTE.violet}" transform="rotate(20 43 13)"/><circle cx="48" cy="42" r="6" fill="${PALETTE.teal}"/><path d="M14 44 L20 56 L8 56 Z" fill="${PALETTE.pink}"/><circle cx="30" cy="30" r="4" fill="${PALETTE.gold}"/>`,
    ),
  });
  out.push({
    slug: "wavy-divider",
    tags: ["divider", "line", "wave"],
    svg: svg(
      `<path d="M2 32c8-14 16 14 24 0s16-14 24 0 10 14 12 0" fill="none" stroke="${PALETTE.violet}" stroke-width="5" stroke-linecap="round"/>`,
    ),
  });
  out.push({
    slug: "dot-grid",
    tags: ["grid", "dots", "pattern"],
    svg: svg(
      Array.from({ length: 4 })
        .flatMap((_, row) =>
          Array.from({ length: 4 }).map(
            (_, col) => `<circle cx="${10 + col * 15}" cy="${10 + row * 15}" r="3.5" fill="${PALETTE.ember}"/>`,
          ),
        )
        .join(""),
    ),
  });
  out.push({
    slug: "frame-corner",
    tags: ["frame", "corner", "border"],
    svg: svg(
      `<path d="M4 24 V4 H24" fill="none" stroke="${PALETTE.teal}" stroke-width="6" stroke-linecap="round"/><path d="M40 60 H60 V40" fill="none" stroke="${PALETTE.teal}" stroke-width="6" stroke-linecap="round"/>`,
    ),
  });
  return out;
}

// ---------- Hero stock photos (provenance: docs/design/ASSETS.md — Unsplash License) ----------

export const HERO_PHOTOS = [
  {
    name: "lake",
    file: "lake-original.webp",
    width: 1600,
    height: 1200,
    url: "https://unsplash.com/photos/F2UvQ-iIqqA",
    tags: ["nature", "lake", "mountains", "travel"],
  },
  {
    name: "beach",
    file: "beach-original.webp",
    width: 1200,
    height: 1500,
    url: "https://unsplash.com/photos/6NHivat8d4w",
    tags: ["beach", "ocean", "summer", "travel"],
  },
  {
    name: "latte",
    file: "latte-original.webp",
    width: 1000,
    height: 1250,
    url: "https://unsplash.com/photos/XOhI_kW_TaM",
    tags: ["coffee", "cafe", "drink"],
  },
  {
    name: "street",
    file: "street-original.webp",
    width: 1000,
    height: 1250,
    url: "https://unsplash.com/photos/uZA3P4sA3tM",
    tags: ["city", "street", "urban"],
  },
  {
    name: "vase",
    file: "vase-original.webp",
    width: 1000,
    height: 1250,
    url: "https://unsplash.com/photos/l0ah3UBLppo",
    tags: ["flowers", "vase", "still-life"],
  },
] as const;

// ---------- Fonts ----------

export const FONTS: { family: string; weights: number[]; license: string; premium?: boolean }[] = [
  { family: "Inter", weights: [400, 700] },
  { family: "Poppins", weights: [400, 700] },
  { family: "Playfair Display", weights: [400, 700] },
  { family: "Bebas Neue", weights: [400] },
  { family: "Caveat", weights: [400, 700] },
  { family: "Bricolage Grotesque", weights: [400, 700, 800] },
  { family: "Geist", weights: [400, 500, 700] },
  { family: "Geist Mono", weights: [400, 500] },
  { family: "Space Grotesk", weights: [400, 700] },
  { family: "DM Sans", weights: [400, 700] },
  { family: "Fraunces", weights: [400, 600] },
  { family: "Sora", weights: [400, 700] },
].map((f) => ({ ...f, license: "OFL-1.1" }));

// ---------- Template node builders (editor-core document, schemaVersion 1) ----------

let seq = 0;
const nid = (p: string) => `${p}${++seq}`;

type AnyNode = Record<string, unknown>;
type Fill =
  | { type: "solid"; color: string }
  | { type: "linear"; angle: number; stops: { offset: number; color: string }[] };

const solid = (color: string): Fill => ({ type: "solid", color });
const linear = (angle: number, a: string, b: string): Fill => ({
  type: "linear",
  angle,
  stops: [
    { offset: 0, color: a },
    { offset: 1, color: b },
  ],
});

function text(o: {
  x: number;
  y: number;
  width: number;
  height: number;
  text: string;
  fontFamily: string;
  fontSize: number;
  fontWeight?: number;
  fill: Fill;
  align?: "left" | "center" | "right";
  letterSpacing?: number;
  lineHeight?: number;
  stroke?: { color: string; width: number };
}): AnyNode {
  return { id: nid("t"), type: "text", ...o };
}

function shape(o: {
  shape: "rect" | "ellipse" | "triangle" | "line" | "star" | "polygon";
  x: number;
  y: number;
  width: number;
  height: number;
  fill?: Fill;
  stroke?: { color: string; width: number };
  cornerRadius?: number;
  opacity?: number;
  rotation?: number;
}): AnyNode {
  return { id: nid("s"), type: "shape", ...o };
}

function photo(o: { assetId: string; x: number; y: number; width: number; height: number }): AnyNode {
  return { id: nid("i"), type: "image", ...o };
}

export interface TemplateSpec {
  slug: string;
  title: string;
  description: string;
  category: string; // TemplateCategory.slug
  sizePreset: SizePresetId;
  style: string[];
  colors: string[];
  tags: string[];
  premium: boolean;
  published: boolean;
  background: Fill | { type: "image"; assetId: string };
  nodes: AnyNode[];
}

/** 25 original templates across all 6 categories. `assets` maps HERO_PHOTOS name -> Asset id. */
export function buildTemplates(assets: Record<string, string>): TemplateSpec[] {
  const ink = "#10112A";
  const white = "#FFFFFF";

  return [
    // ---------------- social-media (5) ----------------
    {
      slug: "summer-sale-post",
      title: "Summer Sale Post",
      description: "Bold gradient announcement for a seasonal sale.",
      category: "social-media",
      sizePreset: "instagram_post",
      style: ["bold", "vibrant"],
      colors: [PALETTE.ember, ink],
      tags: ["sale", "summer", "seasonal"],
      premium: false,
      published: true,
      background: linear(135, PALETTE.ember, ink),
      nodes: [
        text({
          x: 90,
          y: 360,
          width: 900,
          height: 200,
          text: "Summer Sale",
          fontFamily: "Bebas Neue",
          fontSize: 160,
          align: "center",
          fill: solid(white),
        }),
        text({
          x: 90,
          y: 580,
          width: 900,
          height: 80,
          text: "UP TO 50% OFF EVERYTHING",
          fontFamily: "Geist",
          fontSize: 34,
          fontWeight: 700,
          align: "center",
          letterSpacing: 2,
          fill: solid(white),
        }),
        shape({ shape: "rect", x: 390, y: 700, width: 300, height: 72, cornerRadius: 36, fill: solid(white) }),
        text({
          x: 390,
          y: 718,
          width: 300,
          height: 40,
          text: "SHOP NOW",
          fontFamily: "Geist",
          fontSize: 24,
          fontWeight: 700,
          align: "center",
          fill: solid(ink),
        }),
      ],
    },
    {
      slug: "weekend-getaway-story",
      title: "Weekend Getaway Story",
      description: "Full-bleed travel photo with a gradient caption bar.",
      category: "social-media",
      sizePreset: "instagram_story",
      style: ["modern", "minimal"],
      colors: [PALETTE.teal, ink],
      tags: ["travel", "story", "nature"],
      premium: false,
      published: true,
      background: assets.lake ? { type: "image", assetId: assets.lake } : solid(ink),
      nodes: [
        ...(assets.lake ? [photo({ assetId: assets.lake, x: 0, y: 0, width: 1080, height: 1920 })] : []),
        shape({ shape: "rect", x: 0, y: 1500, width: 1080, height: 420, fill: linear(90, "#00000000", "#000000CC") }),
        text({
          x: 70,
          y: 1620,
          width: 940,
          height: 160,
          text: "Weekend\nGetaway",
          fontFamily: "Bricolage Grotesque",
          fontSize: 76,
          fontWeight: 800,
          fill: solid(white),
        }),
        text({
          x: 70,
          y: 1800,
          width: 940,
          height: 60,
          text: "Swipe up for the full itinerary",
          fontFamily: "Geist",
          fontSize: 28,
          fill: solid(white),
        }),
      ],
    },
    {
      slug: "new-arrivals-story",
      title: "New Arrivals Story",
      description: "Playful vertical badge layout for a product drop.",
      category: "social-media",
      sizePreset: "instagram_story",
      style: ["playful", "bold"],
      colors: [PALETTE.violet, PALETTE.pink],
      tags: ["fashion", "new", "arrivals"],
      premium: false,
      published: true,
      background: linear(160, PALETTE.violet, PALETTE.pink),
      nodes: [
        shape({ shape: "ellipse", x: 290, y: 500, width: 500, height: 500, fill: solid("#FFFFFF22") }),
        text({
          x: 140,
          y: 700,
          width: 800,
          height: 220,
          text: "NEW\nARRIVALS",
          fontFamily: "Bebas Neue",
          fontSize: 110,
          align: "center",
          fill: solid(white),
        }),
        shape({ shape: "star", x: 480, y: 1000, width: 120, height: 120, fill: solid(PALETTE.gold) }),
        text({
          x: 140,
          y: 1180,
          width: 800,
          height: 60,
          text: "Tap to shop the drop",
          fontFamily: "Geist",
          fontSize: 32,
          align: "center",
          fill: solid(white),
        }),
      ],
    },
    {
      slug: "product-drop-countdown",
      title: "Product Drop Countdown",
      description: "Dark, high-contrast countdown teaser.",
      category: "social-media",
      sizePreset: "instagram_story",
      style: ["bold", "elegant"],
      colors: [ink, PALETTE.gold],
      tags: ["countdown", "launch", "hype"],
      premium: true,
      published: true,
      background: solid(ink),
      nodes: [
        text({
          x: 90,
          y: 300,
          width: 900,
          height: 60,
          text: "DROPPING IN",
          fontFamily: "Geist",
          fontSize: 30,
          fontWeight: 700,
          align: "center",
          letterSpacing: 4,
          fill: solid(PALETTE.gold),
        }),
        text({
          x: 40,
          y: 650,
          width: 1000,
          height: 400,
          text: "48:00",
          fontFamily: "Bricolage Grotesque",
          fontSize: 220,
          fontWeight: 800,
          align: "center",
          fill: solid(white),
        }),
        shape({ shape: "rect", x: 340, y: 1200, width: 400, height: 84, cornerRadius: 42, fill: solid(PALETTE.gold) }),
        text({
          x: 340,
          y: 1222,
          width: 400,
          height: 40,
          text: "NOTIFY ME",
          fontFamily: "Geist",
          fontSize: 26,
          fontWeight: 700,
          align: "center",
          fill: solid(ink),
        }),
      ],
    },
    {
      slug: "vlog-day-in-my-life",
      title: "Vlog Thumbnail: Day in My Life",
      description: "High-energy YouTube thumbnail with an outlined headline.",
      category: "social-media",
      sizePreset: "youtube_thumbnail",
      style: ["bold", "vibrant"],
      colors: ["#FF3B3B", PALETTE.gold],
      tags: ["youtube", "vlog", "thumbnail"],
      premium: false,
      published: true,
      background: assets.street ? { type: "image", assetId: assets.street } : solid(ink),
      nodes: [
        ...(assets.street ? [photo({ assetId: assets.street, x: 280, y: 0, width: 1000, height: 720 })] : []),
        shape({ shape: "rect", x: 0, y: 0, width: 1280, height: 720, fill: linear(90, "#000000B0", "#00000000") }),
        text({
          x: 40,
          y: 220,
          width: 560,
          height: 300,
          text: "DAY IN\nMY LIFE",
          fontFamily: "Bebas Neue",
          fontSize: 92,
          fill: solid(white),
          stroke: { color: "#FF3B3B", width: 3 },
        }),
        shape({ shape: "rect", x: 40, y: 540, width: 220, height: 56, cornerRadius: 10, fill: solid(PALETTE.gold) }),
        text({
          x: 40,
          y: 554,
          width: 220,
          height: 32,
          text: "EPISODE 12",
          fontFamily: "Geist",
          fontSize: 20,
          fontWeight: 700,
          align: "center",
          fill: solid(ink),
        }),
      ],
    },

    // ---------------- business (4) ----------------
    {
      slug: "modern-minimal-business-card",
      title: "Modern Minimal Business Card",
      description: "Clean two-tone card with a strong name treatment.",
      category: "business",
      sizePreset: "business_card",
      style: ["minimal", "modern"],
      colors: [ink, white],
      tags: ["business-card", "minimal", "corporate"],
      premium: false,
      published: true,
      background: solid(white),
      nodes: [
        shape({ shape: "rect", x: 0, y: 0, width: 24, height: 600, fill: solid(ink) }),
        text({
          x: 80,
          y: 220,
          width: 800,
          height: 70,
          text: "Alex Rivera",
          fontFamily: "Bricolage Grotesque",
          fontSize: 48,
          fontWeight: 700,
          fill: solid(ink),
        }),
        text({
          x: 80,
          y: 290,
          width: 800,
          height: 40,
          text: "Creative Director",
          fontFamily: "Geist",
          fontSize: 22,
          fill: solid("#5E6180"),
        }),
        shape({ shape: "rect", x: 80, y: 350, width: 80, height: 4, fill: solid(PALETTE.ember) }),
        text({
          x: 80,
          y: 380,
          width: 800,
          height: 30,
          text: "hello@studio.example  ·  +1 555 0100",
          fontFamily: "Geist Mono",
          fontSize: 16,
          fill: solid("#5E6180"),
        }),
      ],
    },
    {
      slug: "creative-studio-business-card",
      title: "Creative Studio Business Card",
      description: "Diagonal color block with a bold logo mark.",
      category: "business",
      sizePreset: "business_card",
      style: ["bold", "playful"],
      colors: [PALETTE.ember, "#FFF6EF"],
      tags: ["business-card", "studio", "creative"],
      premium: false,
      published: true,
      background: solid("#FFF6EF"),
      nodes: [
        shape({
          shape: "polygon",
          x: -100,
          y: -100,
          width: 500,
          height: 800,
          rotation: 12,
          fill: solid(PALETTE.ember),
        }),
        shape({ shape: "ellipse", x: 60, y: 90, width: 90, height: 90, fill: solid(white) }),
        text({
          x: 280,
          y: 160,
          width: 700,
          height: 60,
          text: "Nova Studio",
          fontFamily: "Space Grotesk",
          fontSize: 40,
          fontWeight: 700,
          fill: solid(ink),
        }),
        text({
          x: 280,
          y: 220,
          width: 700,
          height: 30,
          text: "Brand & Visual Design",
          fontFamily: "Geist",
          fontSize: 20,
          fill: solid("#5E6180"),
        }),
        text({
          x: 280,
          y: 460,
          width: 700,
          height: 30,
          text: "novastudio.example",
          fontFamily: "Geist Mono",
          fontSize: 16,
          fill: solid(ink),
        }),
      ],
    },
    {
      slug: "quarterly-report-cover",
      title: "Quarterly Report Cover",
      description: "Understated cover slide for an investor update.",
      category: "business",
      sizePreset: "presentation_16_9",
      style: ["elegant", "minimal"],
      colors: ["#1C2333", PALETTE.teal],
      tags: ["report", "slide", "corporate"],
      premium: true,
      published: true,
      background: solid("#1C2333"),
      nodes: [
        shape({ shape: "rect", x: 0, y: 900, width: 1920, height: 10, fill: solid(PALETTE.teal) }),
        text({
          x: 120,
          y: 400,
          width: 1200,
          height: 120,
          text: "Q3 Performance Review",
          fontFamily: "Bricolage Grotesque",
          fontSize: 72,
          fontWeight: 700,
          fill: solid(white),
        }),
        text({
          x: 120,
          y: 520,
          width: 1200,
          height: 50,
          text: "Prepared for the board · October 2026",
          fontFamily: "Geist",
          fontSize: 26,
          fill: solid("#A7A9C7"),
        }),
      ],
    },
    {
      slug: "startup-pitch-title-slide",
      title: "Startup Pitch Title Slide",
      description: "High-contrast gradient opener for a pitch deck.",
      category: "business",
      sizePreset: "presentation_16_9",
      style: ["bold", "modern"],
      colors: [PALETTE.violet, "#2DA8FF"],
      tags: ["pitch", "startup", "slide"],
      premium: true,
      published: true,
      background: solid(ink),
      nodes: [
        shape({
          shape: "ellipse",
          x: 1300,
          y: -200,
          width: 900,
          height: 900,
          fill: linear(45, PALETTE.violet, "#2DA8FF"),
        }),
        text({
          x: 120,
          y: 420,
          width: 1100,
          height: 140,
          text: "Reinventing how\nteams ship",
          fontFamily: "Bricolage Grotesque",
          fontSize: 68,
          fontWeight: 800,
          fill: solid(white),
        }),
        text({
          x: 120,
          y: 620,
          width: 900,
          height: 40,
          text: "Seed round · 2026",
          fontFamily: "Geist Mono",
          fontSize: 24,
          fill: solid("#A7A9C7"),
        }),
      ],
    },

    // ---------------- marketing (4) ----------------
    {
      slug: "flash-sale-flyer",
      title: "Flash Sale Flyer",
      description: "Big percentage callout for a limited-time discount.",
      category: "marketing",
      sizePreset: "flyer_letter",
      style: ["bold", "vibrant"],
      colors: [PALETTE.ember, ink],
      tags: ["flyer", "sale", "discount"],
      premium: false,
      published: true,
      background: solid(white),
      nodes: [
        shape({ shape: "rect", x: 0, y: 0, width: 1700, height: 500, fill: solid(ink) }),
        text({
          x: 100,
          y: 150,
          width: 1500,
          height: 220,
          text: "FLASH SALE",
          fontFamily: "Bebas Neue",
          fontSize: 140,
          align: "center",
          fill: solid(white),
        }),
        text({
          x: 300,
          y: 700,
          width: 1100,
          height: 500,
          text: "50% OFF",
          fontFamily: "Bricolage Grotesque",
          fontSize: 220,
          fontWeight: 800,
          align: "center",
          fill: solid(PALETTE.ember),
        }),
        text({
          x: 300,
          y: 1250,
          width: 1100,
          height: 80,
          text: "THIS WEEKEND ONLY — IN STORE & ONLINE",
          fontFamily: "Geist",
          fontSize: 34,
          fontWeight: 700,
          align: "center",
          letterSpacing: 1,
          fill: solid(ink),
        }),
        shape({ shape: "rect", x: 600, y: 1450, width: 500, height: 100, cornerRadius: 50, fill: solid(ink) }),
        text({
          x: 600,
          y: 1478,
          width: 500,
          height: 44,
          text: "SHOP THE SALE",
          fontFamily: "Geist",
          fontSize: 28,
          fontWeight: 700,
          align: "center",
          fill: solid(white),
        }),
      ],
    },
    {
      slug: "email-newsletter-banner",
      title: "Email Newsletter Banner",
      description: "Split layout banner for a newsletter header.",
      category: "marketing",
      sizePreset: "banner_ad",
      style: ["modern", "minimal"],
      colors: ["#1E3A8A", PALETTE.teal],
      tags: ["newsletter", "email", "banner"],
      premium: true,
      published: true,
      background: solid("#1E3A8A"),
      nodes: [
        shape({ shape: "ellipse", x: 900, y: -100, width: 500, height: 500, fill: solid("#2DA8FF55") }),
        text({
          x: 80,
          y: 180,
          width: 700,
          height: 70,
          text: "This Week's Picks",
          fontFamily: "Bricolage Grotesque",
          fontSize: 48,
          fontWeight: 700,
          fill: solid(white),
        }),
        text({
          x: 80,
          y: 260,
          width: 700,
          height: 40,
          text: "Curated drops, fresh off the press",
          fontFamily: "Geist",
          fontSize: 22,
          fill: solid("#CBD5F5"),
        }),
        shape({ shape: "rect", x: 80, y: 340, width: 220, height: 56, cornerRadius: 28, fill: solid(PALETTE.teal) }),
        text({
          x: 80,
          y: 358,
          width: 220,
          height: 30,
          text: "Read more",
          fontFamily: "Geist",
          fontSize: 20,
          fontWeight: 700,
          align: "center",
          fill: solid(ink),
        }),
      ],
    },
    {
      slug: "limited-time-offer-pin",
      title: "Limited Time Offer Pin",
      description: "Vertical stacked type for a Pinterest-style offer pin.",
      category: "marketing",
      sizePreset: "pinterest_pin",
      style: ["bold", "playful"],
      colors: [PALETTE.pink, PALETTE.violet],
      tags: ["pin", "offer", "limited"],
      premium: true,
      published: true,
      background: linear(180, PALETTE.pink, PALETTE.violet),
      nodes: [
        shape({ shape: "ellipse", x: 350, y: 60, width: 300, height: 300, fill: solid("#FFFFFF22") }),
        text({
          x: 100,
          y: 400,
          width: 800,
          height: 240,
          text: "LIMITED\nTIME\nOFFER",
          fontFamily: "Bebas Neue",
          fontSize: 100,
          align: "center",
          fill: solid(white),
        }),
        text({
          x: 100,
          y: 1250,
          width: 800,
          height: 60,
          text: "Ends Sunday at midnight",
          fontFamily: "Geist",
          fontSize: 30,
          align: "center",
          fill: solid(white),
        }),
      ],
    },
    {
      slug: "conference-poster",
      title: "Conference Poster",
      description: "Headline + schedule blocks for an event poster.",
      category: "marketing",
      sizePreset: "poster",
      style: ["bold", "modern"],
      colors: ["#0E1B3D", PALETTE.ember],
      tags: ["conference", "poster", "event"],
      premium: false,
      published: true,
      background: solid("#0E1B3D"),
      nodes: [
        text({
          x: 120,
          y: 220,
          width: 1560,
          height: 300,
          text: "FUTURE\nFORWARD",
          fontFamily: "Bebas Neue",
          fontSize: 180,
          fill: solid(white),
        }),
        text({
          x: 120,
          y: 760,
          width: 1560,
          height: 60,
          text: "A one-day conference on what's next in tech",
          fontFamily: "Geist",
          fontSize: 38,
          fill: solid(PALETTE.ember),
        }),
        shape({ shape: "rect", x: 120, y: 900, width: 1560, height: 4, fill: solid(PALETTE.ember) }),
        text({
          x: 120,
          y: 960,
          width: 1560,
          height: 50,
          text: "NOV 14 · CONVENTION CENTER · 9AM–6PM",
          fontFamily: "Geist Mono",
          fontSize: 30,
          letterSpacing: 2,
          fill: solid(white),
        }),
      ],
    },

    // ---------------- events (4) ----------------
    {
      slug: "beach-party-invitation",
      title: "Beach Party Invitation",
      description: "Sunny photo invitation for a beach celebration.",
      category: "events",
      sizePreset: "invitation",
      style: ["playful", "vibrant"],
      colors: [PALETTE.gold, "#2DA8FF"],
      tags: ["invitation", "beach", "party"],
      premium: false,
      published: true,
      background: assets.beach ? { type: "image", assetId: assets.beach } : solid("#2DA8FF"),
      nodes: [
        ...(assets.beach ? [photo({ assetId: assets.beach, x: 0, y: 0, width: 1200, height: 1800 })] : []),
        shape({ shape: "rect", x: 0, y: 1300, width: 1200, height: 500, fill: linear(90, "#00000000", "#00000099") }),
        text({
          x: 80,
          y: 1400,
          width: 1040,
          height: 140,
          text: "Beach Party",
          fontFamily: "Caveat",
          fontSize: 100,
          fontWeight: 700,
          align: "center",
          fill: solid(white),
        }),
        text({
          x: 80,
          y: 1560,
          width: 1040,
          height: 60,
          text: "Saturday · 4PM · Sunset Shore",
          fontFamily: "Geist",
          fontSize: 32,
          align: "center",
          fill: solid(white),
        }),
      ],
    },
    {
      slug: "save-the-date-wedding",
      title: "Save the Date Wedding",
      description: "Elegant floral invitation with a soft serif headline.",
      category: "events",
      sizePreset: "invitation",
      style: ["elegant", "minimal"],
      colors: ["#F6E2DE", PALETTE.gold],
      tags: ["wedding", "invitation", "elegant"],
      premium: true,
      published: true,
      background: solid("#FBF3F0"),
      nodes: [
        ...(assets.vase ? [photo({ assetId: assets.vase, x: 200, y: 80, width: 800, height: 760 })] : []),
        shape({
          shape: "rect",
          x: 60,
          y: 60,
          width: 1080,
          height: 1680,
          stroke: { color: PALETTE.gold, width: 2 },
          fill: solid("#00000000"),
        }),
        text({
          x: 100,
          y: 900,
          width: 1000,
          height: 100,
          text: "Save the Date",
          fontFamily: "Playfair Display",
          fontSize: 72,
          align: "center",
          fill: solid("#5E3B33"),
        }),
        text({
          x: 100,
          y: 1020,
          width: 1000,
          height: 60,
          text: "Mia & Daniel  ·  June 20, 2027",
          fontFamily: "Fraunces",
          fontSize: 32,
          align: "center",
          fill: solid("#5E3B33"),
        }),
      ],
    },
    {
      slug: "charity-gala-poster",
      title: "Charity Gala Poster",
      description: "Deep, formal poster for an evening fundraiser.",
      category: "events",
      sizePreset: "poster",
      style: ["elegant", "bold"],
      colors: ["#2B1B4D", PALETTE.gold],
      tags: ["gala", "charity", "poster"],
      premium: true,
      published: true,
      background: solid("#2B1B4D"),
      nodes: [
        shape({
          shape: "rect",
          x: 150,
          y: 150,
          width: 1500,
          height: 2400,
          stroke: { color: PALETTE.gold, width: 3 },
          fill: solid("#00000000"),
        }),
        text({
          x: 250,
          y: 900,
          width: 1300,
          height: 300,
          text: "An Evening\nof Hope",
          fontFamily: "Playfair Display",
          fontSize: 130,
          align: "center",
          fill: solid(white),
        }),
        text({
          x: 250,
          y: 1300,
          width: 1300,
          height: 60,
          text: "Annual Charity Gala · December 5",
          fontFamily: "Geist",
          fontSize: 36,
          align: "center",
          fill: solid(PALETTE.gold),
        }),
      ],
    },
    {
      slug: "birthday-bash-invitation",
      title: "Birthday Bash Invitation",
      description: "Pastel confetti invitation for a birthday party.",
      category: "events",
      sizePreset: "invitation",
      style: ["playful", "vibrant"],
      colors: [PALETTE.pink, PALETTE.gold, PALETTE.teal],
      tags: ["birthday", "party", "invitation"],
      premium: false,
      published: true,
      background: solid("#FFF8F0"),
      nodes: [
        shape({ shape: "ellipse", x: 80, y: 120, width: 70, height: 70, fill: solid(PALETTE.pink) }),
        shape({ shape: "ellipse", x: 1000, y: 200, width: 50, height: 50, fill: solid(PALETTE.teal) }),
        shape({ shape: "star", x: 900, y: 1500, width: 90, height: 90, fill: solid(PALETTE.gold) }),
        shape({ shape: "ellipse", x: 150, y: 1550, width: 60, height: 60, fill: solid(PALETTE.violet) }),
        text({
          x: 100,
          y: 700,
          width: 1000,
          height: 220,
          text: "Let's Party!",
          fontFamily: "Caveat",
          fontSize: 130,
          fontWeight: 700,
          align: "center",
          fill: solid("#5E3B33"),
        }),
        text({
          x: 100,
          y: 950,
          width: 1000,
          height: 60,
          text: "Join us to celebrate turning 7!",
          fontFamily: "Geist",
          fontSize: 32,
          align: "center",
          fill: solid("#5E3B33"),
        }),
      ],
    },

    // ---------------- education (4) ----------------
    {
      slug: "back-to-school-presentation",
      title: "Back to School Presentation",
      description: "Bright opener slide for a classroom presentation.",
      category: "education",
      sizePreset: "presentation_16_9",
      style: ["playful", "vibrant"],
      colors: [PALETTE.teal, PALETTE.gold],
      tags: ["school", "presentation", "education"],
      premium: false,
      published: true,
      background: solid("#FFFFFF"),
      nodes: [
        shape({ shape: "rect", x: 0, y: 0, width: 1920, height: 180, fill: solid(PALETTE.teal) }),
        shape({ shape: "ellipse", x: 1650, y: 700, width: 220, height: 220, fill: solid(PALETTE.gold) }),
        shape({ shape: "star", x: 120, y: 750, width: 150, height: 150, fill: solid(PALETTE.pink) }),
        text({
          x: 120,
          y: 400,
          width: 1400,
          height: 140,
          text: "Welcome Back to School!",
          fontFamily: "Bricolage Grotesque",
          fontSize: 76,
          fontWeight: 800,
          fill: solid(ink),
        }),
        text({
          x: 120,
          y: 540,
          width: 1200,
          height: 50,
          text: "Mrs. Carter's 4th Grade Class · Fall 2026",
          fontFamily: "Geist",
          fontSize: 28,
          fill: solid("#5E6180"),
        }),
      ],
    },
    {
      slug: "student-resume-template",
      title: "Student Resume Template",
      description: "Classic single-column resume with clear section dividers.",
      category: "education",
      sizePreset: "resume_a4",
      style: ["minimal", "elegant"],
      colors: [ink, "#5E6180"],
      tags: ["resume", "cv", "student"],
      premium: false,
      published: true,
      background: solid(white),
      nodes: [
        text({
          x: 100,
          y: 90,
          width: 1040,
          height: 70,
          text: "Jordan Lee",
          fontFamily: "Bricolage Grotesque",
          fontSize: 56,
          fontWeight: 700,
          fill: solid(ink),
        }),
        text({
          x: 100,
          y: 160,
          width: 1040,
          height: 36,
          text: "jordan.lee@email.example  ·  (555) 010-0100  ·  Portfolio: jordanlee.example",
          fontFamily: "Geist Mono",
          fontSize: 18,
          fill: solid("#5E6180"),
        }),
        shape({ shape: "rect", x: 100, y: 230, width: 1040, height: 3, fill: solid(ink) }),
        text({
          x: 100,
          y: 270,
          width: 1040,
          height: 40,
          text: "EDUCATION",
          fontFamily: "Geist",
          fontSize: 24,
          fontWeight: 700,
          letterSpacing: 2,
          fill: solid(ink),
        }),
        text({
          x: 100,
          y: 320,
          width: 1040,
          height: 60,
          text: "B.A. in Graphic Design — Riverside State University, 2027",
          fontFamily: "Geist",
          fontSize: 22,
          fill: solid("#5E6180"),
        }),
        text({
          x: 100,
          y: 440,
          width: 1040,
          height: 40,
          text: "EXPERIENCE",
          fontFamily: "Geist",
          fontSize: 24,
          fontWeight: 700,
          letterSpacing: 2,
          fill: solid(ink),
        }),
        text({
          x: 100,
          y: 490,
          width: 1040,
          height: 100,
          text: "Design Intern — Studio North (2026)\nAssisted on brand identity and social templates.",
          fontFamily: "Geist",
          fontSize: 22,
          fill: solid("#5E6180"),
        }),
      ],
    },
    {
      slug: "online-course-thumbnail",
      title: "Online Course Thumbnail",
      description: "Clear, clickable thumbnail for an online lesson.",
      category: "education",
      sizePreset: "youtube_thumbnail",
      style: ["bold", "modern"],
      colors: [PALETTE.teal, PALETTE.gold],
      tags: ["course", "education", "thumbnail"],
      premium: true,
      published: true,
      background: linear(90, "#0E3B3A", PALETTE.teal),
      nodes: [
        shape({ shape: "polygon", x: 900, y: 260, width: 220, height: 200, fill: solid(white) }),
        text({
          x: 60,
          y: 180,
          width: 760,
          height: 220,
          text: "Learn to\nCode in 30\nDays",
          fontFamily: "Bricolage Grotesque",
          fontSize: 60,
          fontWeight: 800,
          fill: solid(white),
        }),
        shape({ shape: "rect", x: 60, y: 560, width: 240, height: 60, cornerRadius: 10, fill: solid(PALETTE.gold) }),
        text({
          x: 60,
          y: 578,
          width: 240,
          height: 32,
          text: "FREE LESSON",
          fontFamily: "Geist",
          fontSize: 20,
          fontWeight: 700,
          align: "center",
          fill: solid(ink),
        }),
      ],
    },
    {
      slug: "study-planner-cover",
      title: "Study Planner Cover",
      description: "Soft pastel grid cover for a study planner deck.",
      category: "education",
      sizePreset: "presentation_16_9",
      style: ["minimal", "elegant"],
      colors: ["#EDE9FE", PALETTE.violet],
      tags: ["planner", "study", "cover"],
      premium: false,
      published: true,
      background: solid("#F4F1FE"),
      nodes: [
        ...Array.from({ length: 6 }).map((_, i) =>
          shape({
            shape: "rect",
            x: 120 + i * 280,
            y: 760,
            width: 240,
            height: 240,
            cornerRadius: 24,
            fill: solid(i % 2 === 0 ? "#E4DCFF" : "#D8CCFF"),
          }),
        ),
        text({
          x: 120,
          y: 280,
          width: 1200,
          height: 120,
          text: "My Study Planner",
          fontFamily: "Sora",
          fontSize: 64,
          fontWeight: 700,
          fill: solid("#3C2F70"),
        }),
        text({
          x: 120,
          y: 400,
          width: 900,
          height: 50,
          text: "Fall semester · Weekly goals & schedule",
          fontFamily: "Geist",
          fontSize: 28,
          fill: solid("#5E6180"),
        }),
      ],
    },

    // ---------------- ecommerce (4) ----------------
    {
      slug: "product-showcase-square",
      title: "Product Showcase Square",
      description: "Minimal product stage with a corner badge.",
      category: "ecommerce",
      sizePreset: "product_square",
      style: ["minimal", "modern"],
      colors: [white, PALETTE.ember],
      tags: ["product", "ecommerce", "showcase"],
      premium: false,
      published: true,
      background: solid("#F7F7FA"),
      nodes: [
        shape({ shape: "ellipse", x: 200, y: 200, width: 600, height: 600, fill: solid(white) }),
        shape({ shape: "rect", x: 400, y: 380, width: 200, height: 260, cornerRadius: 24, fill: solid(PALETTE.ember) }),
        shape({ shape: "ellipse", x: 760, y: 60, width: 160, height: 160, fill: solid(ink) }),
        text({
          x: 760,
          y: 112,
          width: 160,
          height: 60,
          text: "NEW",
          fontFamily: "Geist",
          fontSize: 24,
          fontWeight: 700,
          align: "center",
          fill: solid(white),
        }),
      ],
    },
    {
      slug: "new-collection-banner",
      title: "New Collection Banner",
      description: "Bold type banner announcing a new product line.",
      category: "ecommerce",
      sizePreset: "banner_ad",
      style: ["bold", "elegant"],
      colors: [ink, PALETTE.gold],
      tags: ["collection", "banner", "ecommerce"],
      premium: true,
      published: true,
      background: solid(ink),
      nodes: [
        shape({ shape: "polygon", x: 900, y: -50, width: 500, height: 730, rotation: 8, fill: solid(PALETTE.gold) }),
        text({
          x: 70,
          y: 240,
          width: 760,
          height: 150,
          text: "NEW\nCOLLECTION",
          fontFamily: "Bebas Neue",
          fontSize: 72,
          fill: solid(white),
        }),
        text({
          x: 70,
          y: 420,
          width: 700,
          height: 40,
          text: "Fall / Winter 2026",
          fontFamily: "Geist",
          fontSize: 26,
          fill: solid(PALETTE.gold),
        }),
      ],
    },
    {
      slug: "discount-badge-post",
      title: "Discount Badge Post",
      description: "Circular discount badge for a feed post.",
      category: "ecommerce",
      sizePreset: "instagram_post",
      style: ["bold", "vibrant"],
      colors: ["#E8233A", white],
      tags: ["discount", "badge", "ecommerce"],
      premium: false,
      published: true,
      background: solid("#FFF2F2"),
      nodes: [
        shape({ shape: "ellipse", x: 190, y: 190, width: 700, height: 700, fill: solid("#E8233A") }),
        shape({
          shape: "ellipse",
          x: 260,
          y: 260,
          width: 560,
          height: 560,
          stroke: { color: white, width: 6 },
          fill: solid("#00000000"),
        }),
        text({
          x: 190,
          y: 420,
          width: 700,
          height: 180,
          text: "30%\nOFF",
          fontFamily: "Bricolage Grotesque",
          fontSize: 110,
          fontWeight: 800,
          align: "center",
          fill: solid(white),
        }),
        text({
          x: 190,
          y: 980,
          width: 700,
          height: 50,
          text: "Today only — use code SAVE30",
          fontFamily: "Geist",
          fontSize: 30,
          align: "center",
          fill: solid(ink),
        }),
      ],
    },
    {
      slug: "shop-the-look-story",
      title: "Shop the Look Story",
      description: "Lifestyle photo with product tag chips (draft — pending final tag copy).",
      category: "ecommerce",
      sizePreset: "instagram_story",
      style: ["modern", "minimal"],
      colors: ["#5E6180", white],
      tags: ["shop", "lookbook", "story"],
      premium: true,
      published: false,
      background: assets.street ? { type: "image", assetId: assets.street } : solid("#5E6180"),
      nodes: [
        ...(assets.street ? [photo({ assetId: assets.street, x: 40, y: 200, width: 1000, height: 1250 })] : []),
        shape({ shape: "rect", x: 300, y: 600, width: 220, height: 64, cornerRadius: 32, fill: solid(white) }),
        text({
          x: 300,
          y: 620,
          width: 220,
          height: 30,
          text: "Jacket · $120",
          fontFamily: "Geist",
          fontSize: 18,
          fontWeight: 700,
          align: "center",
          fill: solid(ink),
        }),
        text({
          x: 70,
          y: 1550,
          width: 940,
          height: 80,
          text: "Shop the Look",
          fontFamily: "Bricolage Grotesque",
          fontSize: 56,
          fontWeight: 700,
          fill: solid(white),
        }),
      ],
    },
  ];
}
